# Generated by Django 4.2.1 on 2023-05-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('NC', 'New Cairo'), ('AP', 'Abdou Pasha')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SL', 'Silk'), ('CO', 'Cotton'), ('CH', 'Chiffon')], max_length=20),
        ),
    ]
